### ISSUE TITLE
Please add my German locale

### ISSUE THREAD

**Issue by milupo** [Infocatcher/Right_Links#18]
Hello Infocatcher,

I made the German translation of Right Links 0.3.8.4. Please add it to the next version of Right Links.

You will find file right_links-0.3.8.4-locale_de.zip containing the locale folder with the de folder and the two rl files:

http://www.sorbzilla.de/erweiterungen/right_links-0.3.8.4-locale_de.zip

Thank you in advance.

Regards,
milupo

**Comment by Infocatcher** [comment]
Thanks!

**Comment by Infocatcher** [comment]
Please translate recently added string:
```diff
 <!ENTITY rl.loadInBackground "Load links in background">
+<!ENTITY rl.loadBookmarksInBackground "Load bookmarks in background">
```
(https://github.com/Infocatcher/Right_Links/commit/a6c88f1ea02b6ff549402da6f07be2ed5b405410#diff-b8cb38984ecdd455e6ddb04684dde2b8)

This is separate option for bookmarks.

**Comment by Infocatcher** [comment]
@milupo
Oh, yet another change...

```diff
+# First disabling using hotkey, extensions.rightlinks.enabled.confirmHotkey preference
+turnOff=Turn off Right Links?
+turnOffAndDontAsk=Turn off and don't ask confirmation again
```
(https://github.com/Infocatcher/Right_Links/commit/0250950a074614b850c113a95fbf1e4d23981f0d#diff-dd8a8db3fd37448ff1497b46b800a2ac)
