### ISSUE TITLE
Suppress context menu?

### ISSUE THREAD

**Issue by grumpygeek** [Infocatcher/Right_Links#43]
I can't  find any setting to suppress opening of it in the WebExtension version.  Using 0.5b9 on Fx 72.1 on Windows10 laptop with touchpad.  Note that the tab does open in background; it's just annoying to also have the menu popup.  Is this able to be set by user or fixable by dev?

**Comment by Infocatcher** [comment]
Strange, context menu not appears for me... but with desktop Windows 7.
May be something related to laptop-specific things. Or some conflict with another extension.

**Comment by grumpygeek** [comment]
It started working OK (right click works and no popup) today in Waterfox Current.  Still shows 0.5b9 but shows as updated Oct 14.  Haven't checked Firefox yet, last I checked that was having same issue reported by asleepysamurai, but I think you probably got it fixed now (fingers crossed.)
